### ISSUE TITLE
.opus files are not working well

### ISSUE THREAD

**Issue by roraechi** [PaulWoitaschek/MaterialAudiobookPlayer#310]
I have a problem, listenig to .opus files. (mp3 and ogg, for example, is doing right). My phone is a Samsung Galaxy S3 LTE with Cyanogenmod 12.1 (build from August 2015). The MaterialAudiobookPlayer detects the .opus file well and opens it. The problem is, that the speed it plays the audio file is extremely low, even when the setting is on 100% in the players settings. Speeding up in the settings isn't helpfull, because the result is not understandable. Plus it has a lot of white noise.

I tested the same audiofile with other players like vlc media player, ex file explorer or the "music" app of cynaogenmod. They are all working well. 

(Sorry for my bad english. And this is my first action on github. So, if I done something wrong, excuse me.)

**Comment by kRush-** [comment]
Same issue, except for me, playback was too fast on top of the noise.
Example file: http://alternativlos.cdn.as250.net/alternativlos-35.opus
Moto E, CM 12.1

**Comment by Ph1b** [comment]
Seems like an upstream bug with MediaExtractor.

**Comment by micressor** [comment]
Is there a link to a bugreport for MediaExtractor?

This bug should not be closed, until it works with MaterialAudiobookPlayer or has a representative link to a bug assigned.

Thanks.

**Comment by Ph1b** [comment]
As I don't face the problem it would be great if someone could investigate in this.

**Comment by micressor** [comment]
I am not familiar with android development. But I'd like to help to debug this. I use also the opensource [vanilla music](https://github.com/vanilla-music/vanilla) player. May be you can compare the playout methods of MaterialAudiobookPlayer and vanilla music!?

My test was on a cyanogenmod 12.1 (based on Android 5.1), according to #316

**Comment by Ph1b** [comment]
Vanilla Music Player simply uses the android [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) where we use [MediaCodec](https://developer.android.com/reference/android/media/MediaCodec.html) so this is the main difference.

**Comment by Dain42** [comment]
I'm also seeing issues with .opus files. I'd like to offer to help out if I can. I don't have any direct familiarity with Android development, but I work in IT (specifically am a net/sysadmin for a small organization), so I have a decent level of competency with troubleshooting issues, as long as I know what's needed.

My issue is much more basic, though, namely that .opus files are not displaying in the application at all. If this fits better as a new issue I can move it there. I'm seeing this on multiple devices running multiple versions of Android (XT1096 running 5.1 and a Galaxy Nexus Toro running 4.2.2). I *am* seeing these files in multiple other audiobook applications, and I'm able to play them in various media applications on the desktop and phone, including VLC, so I don't think it's an issue of improper encoding.

I'm sorry if I'm just being blind to something simple that I've set or done incorrectly. And again, I hope this fits in this particular issue report, given that it also relates to opus files in this app and that there are no other open issues I could see involving opus files.

**Comment by PaulWoitaschek** [comment]
VLC uses its own encoding. Either this is fixed upstream in AOSP or this stays unfixed unfortunatelly.

**Comment by micressor** [comment]
I've just tested again with version 2.5.0.8 (from f-droid.org). It does still not work. It plays too fast.

This bug should not be closed, until it works with MaterialAudiobookPlayer or has a representative link to a bug assigned.

**Comment by PaulWoitaschek** [comment]
[Upstream](https://code.google.com/p/android/issues/detail?id=80729), nobody seems to care about it.

Works for me on Android 6 .

**Comment by micressor** [comment]
Perfect. This link is a good reference. Thanks.
